### ISSUE TITLE
Sort order of the static/required_magento_patches.json list

### ISSUE THREAD

**Issue by 7ochem** [Hypernode/tools.hypernode.com#8]
There is this Python tool [`tools/patch_spreadsheet_to_json.py`](https://github.com/Hypernode/tools.hypernode.com/blob/master/tools/patch_spreadsheet_to_json.py) to convert that Google Spreadsheet list into the JSON of the `static/required_magento_patches.json` list.

However, the commit 87e92d050293410fd9774ea1dbe7683f212b9089 by @EmPeWe messed up the order of things in there. Though the output of the tools/patch_spreadsheet_to_json.py is also not really neatly sorted.

Changing the order makes it really hard to see the actual changes in the diff of commits.

Can we stick to a certain sorting order? CE first, then EE? Highest version to lowest version?

Also the `tools/patch_spreadsheet_to_json.py` needs a fix to respect this sorting (CE first, then EE, and natural sort versions by key, reversed)

**Comment by gwillem** [comment]
Fixed in 7f44bf1e208d2eebc2b4fdc89632f110d1bdbb2b
