### ISSUE TITLE
Add SUPEE-10570 to the patch list

### ISSUE THREAD

**Issue by diazwatson** [Hypernode/tools.hypernode.com#9]
I can see you are not longer adding the patches to the static .json file but instead reading directly from the spreadsheet.

But, why the [SUPEE-10570](https://magento.com/security/patches/supee-10570) does not show when running the `hypernode:patches:list` command?

**Comment by vdloo** [comment]
should be fixed now, see [this PR](https://github.com/Hypernode/tools.hypernode.com/pull/10)

```
app@83f000-hypernode-magweb-do:~/public$ magerun hypernode:patches:list
+-------------+----------+---------+
| Patch       | Type     | Applied |
+-------------+----------+---------+
| SUPEE-10570 | required | No      |
+-------------+----------+---------+
```

**Comment by diazwatson** [comment]
Nice Thanks
